[global] 로컬 테스트 환경 리다이렉트 url 변경기능 추가
themoment-team/hellogsm-server-24 pull request #124
Opened 2024-08-19 01:39 UTC by tlsgmltjd

## 개요

로그인 성공시 `X-HG-ENV` 헤더 값에 따라 로컬 테스트 환경 url로 리다이렉트 되도록 변경하였습니다.

테스트를 진행할 마땅한 방법을 찾지 못해 테스트를 진행 해보지는 못하였습니다..

2024-08-19 04:09 UTC, jyeonjyan commented on src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
> +        String dryrun = request.getHeader("X-HG-ENV");
`X-HG-ENV` 와 같이 자체 정의한 header 값은 `HeaderConstant` 정도의 클래스로 정리하는게 좋겠습니다.

2024-08-19 04:21 UTC, jyeonjyan commented on src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
> +            return isDryrun ? redirectDryRunBaseUri : redirectBaseUri;
삼항연산자를 여기서 쓰는건, 분기안에서 분기처리하는거라 다소 직관성이 떨어지는 것 같습니다.
그리고 어드민 페이지 리다이렉트도 마찬가지로 local 개발환경에서는 localhost:3000 으로 리턴되어야 할 것 같은데요.
그래서 이런 요구사항 기반으로는 다음과 같은 코드로 수정할것을 제안드려봅니다.

```java
private String getTargetUrl(boolean isAdmin, boolean isDryRun) {
  if(isDryRun) { return "localhost:3000" } // 적절한 상수로 대체
  return isAdmin 
             ? hgAdminRedirectUri 
             : hgStudentRedirectUri;
}
```

2024-08-19 04:25 UTC, jyeonjyan commented on src/main/resources/application.yml
> +  redirect-base-uri: http://localhost:8080
```yml
auth:

```

2024-08-20 01:04 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
> +        String dryrun = request.getHeader("X-HG-ENV");
d22d88b82c77498ee66275fe2463b35f876e30c1

Enum 클래스를 추가하여 정리해보았습니다.

2024-08-20 01:04 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/global/security/handler/CustomUrlAuthenticationSuccessHandler.java
> +            return isDryrun ? redirectDryRunBaseUri : redirectBaseUri;
87079eb10dd3e932296421a42efd971427a69948

더 직관적인 방식 제안 감사드립니다! 변경하였습니다.

2024-08-20 01:05 UTC, tlsgmltjd commented on src/main/resources/application.yml
> +  redirect-base-uri: http://localhost:8080
1e996ffd3e49ca01206b555c9059059ada1744b9

제안해주신 방식대로 반영하였습니다!

2024-08-21 02:19 UTC, jangwooooo submitted a review, later dismissed
수고하셨습니다 👍

2024-08-26 01:22 UTC, jyeonjyan requested changes

2024-08-26 01:22 UTC, jyeonjyan commented on src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
> +    X_H_ENV("X-HG-ENV");
enum type 에 오타가 있는 것 같은데요, 확인 부탁드립니다.
```suggestion
    X_HG_ENV("X-HG-ENV");
```

2024-08-26 01:23 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/global/security/data/HeaderConstant.java
> +    X_H_ENV("X-HG-ENV");
확인 감사드립니다 suggestion 반영하겠습니다.

2024-08-26 01:25 UTC, jangwooooo approved these changes

2024-08-26 01:27 UTC, merged