[oneseo] 원서 추가 기능 구현
themoment-team/hellogsm-server-24 pull request #64
Opened 2024-07-05 06:39 UTC by tlsgmltjd

## 개요

원서 추가 기능을 구현하였습니다.

## 본문

- `/onseo/me` 원서 추가 기능을 구현하였습니다. 
- `Oneseo` 엔티티의 식별 관계인 `OneseoPrivacyDetail`, `MiddleSchoolAchievement` 엔티티를 생성 후 저장합니다.

2024-07-06 08:46 UTC, jangwooooo requested changes

2024-07-06 08:46 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +
`tb_oneseo_privacy_detail`의 보호자와의 관계 column인 `relationship_with_guardian`과 네이밍이 일치하도록 수정하는게 좋을 거 같아요.

2024-07-06 08:46 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +
여기도 db column 네임과 일치하도록 `school` prefix 붙이는 게 좋아 보여요.

2024-07-06 08:46 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
> +    private static Oneseo buildOneseo(OneseoReqDto reqDto, Member currentMember) {
내부에서 사용하는 build 메서드에 `static`을 사용하신 이유가 있으신가요? 
`static` 키워드를 사용하지 않아도 execute 메서드 내에서 호출이 가능할 것 같습니다.

2024-07-06 08:46 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
> +
`Oneseo`뿐 아니라 다른 엔티티도 저장하기에 `svaeOneseo`라는 이름은 혼동을 줄 수 있다고 생각해요.
`saveEntites` or `saveOneseoWithDetails` 정도 추천드립니다. 저는 `saveEntities` 선호..

2024-07-06 08:46 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +        String middleSchoolGrade,
db column과 일치하도록 `transcript`로 수정 제안드립니다.

2024-07-06 09:06 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
> +    }
기존 코드 포맷과 동일하도록 `build();`전에 개행 하시는 게 좋아 보여요.

2024-07-06 17:50 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +
4e63cb48bd1591cde0cf171036910fbe2f042672 넵 위의 리뷰와 함께 dto 필드명 변경 후 API 문서에도 반영하였습니다!

2024-07-06 17:51 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
> +    private static Oneseo buildOneseo(OneseoReqDto reqDto, Member currentMember) {
936b88399817ad0d096a002600b39b291c0d544a

인텔리제이 메서드 분리 단축키를 사용하여 메서드를 생성하였는데 static 키워드가 붙었나보네요..
확인 감사드립니다. 제거하였습니다!

2024-07-06 17:51 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
> +
addcc5146bbcb1c343df6935957854489caf2ac5

넵 저도 메서드 명을 고민하였는데 좋은 의견 감사드립니다. saveEntities로 반영하였습니다!

2024-07-06 17:52 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +        String middleSchoolGrade,
6bff0dffbf72d83b597e7ced9207905f179d574b

넵 반영 후 API 문서에도 적용하였습니다.

2024-07-06 17:52 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/service/CreateOneseoService.java
> +    }
2ca9e54c3a01cb644f89e79c38f24fa0b2ff75e4

반영하였습니다!

2024-07-07 06:39 UTC, jangwooooo commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +        String schoolTeacherName,
해당 정규식이 `공백으로 이루어지지 않은 문자열`을 뜻하는 것으로 보입니다.
특별한 이유가 있는 게 아니라면, `@NotBlank`사용이 더 가독성이 뛰어날 거 같습니다.

2024-07-07 07:00 UTC, tlsgmltjd commented on src/main/java/team/themoment/hellogsmv3/domain/oneseo/dto/request/OneseoReqDto.java
> +        String schoolTeacherName,
7beb1c80f07c1f713e5953f5ee71dbb7b744ed67

확인 감사드립나다! 해당 어노테이션으로 변경하였습니다.

2024-07-07 07:44 UTC, jangwooooo submitted a review, later dismissed
수고하셨어요 👍

2024-07-08 07:56 UTC, jangwooooo approved these changes

2024-07-08 08:46 UTC, merged